apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: row-major-web
  name: row-major-web-content-deployment
spec:
  template:
    spec:
      containers:
      - name: row-major-web-content
        image: us-west1-docker.pkg.dev/row-major-ci/row-major-net-images/webalator:2b1af10898d2b9ea0ee12211864b98dcd93c35f6
