# This file is overwritten by CI.
#
# Refer to //infra-tools/bump-manifest to see how it is generated.
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: medtracker
  name: poller
spec:
  template:
    spec:
      containers:
      - name: main
        image: us-west1-docker.pkg.dev/row-major-ci/row-major-net-images/medtracker/poller:c0418fc1686a3c1e64c334f4d4b506508c826c00
