name: row-major-web-deploy
on:
  push:
  workflow_dispatch:

jobs:
  deploy-row-major-manifest:
    if: "contains(github.event.head_commit.message, 'Deploy-RowMajorWeb: True')"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/508647401058/locations/global/workloadIdentityPools/ci-federation/providers/github-actions'
        service_account: 'github-actions@row-major-ci.iam.gserviceaccount.com'
    - uses: google-github-actions/setup-gcloud@v1
      with:
        version: '>= 390.0.0'
    - run: 'gcloud components install gke-gcloud-auth-plugin'
    - run: 'gcloud container clusters get-credentials --project=bomsync-214520 --billing-project=bomsync-214520 --zone=us-west1 cell-us-west1'
    - run: 'kubectl apply --kustomize=manifests/row-major-web/production'  